#!/bin/sh
xrandr --output DP-2-1 --mode 1920x1080 --pos 3840x0 --rotate right --output DP-2-2 --mode 1920x1080 --pos 1920x592 --rotate normal --output DP-2-3 --mode 1920x1080 --pos 0x592 --rotate normal --output eDP-1 --off --output HDMI-2 --off --output HDMI-1 --off --output DP-2 --off --output DP-1 --off
